
      // 
      // Javascript generated by HTML2 Toolkit plugin
      // 
      var tree;
      
      function treeInit() {
      tree = new YAHOO.widget.TreeView("treeDiv1");
      var root = tree.getRoot();

      
var objd66e60 = {
  label: " DITA For Small Teams",
  href: "topics/dita-for-small-teams.html", 
  target:"contentwin"
};
var d66e60 = new YAHOO.widget.TextNode(objd66e60, root, false);
var d74e3 = new YAHOO.widget.TextNode("Index", root, false);

      
      tree.draw(); 
      } 
      
      YAHOO.util.Event.addListener(window, "load", treeInit);       
    